/**
 * Cascade Apartment 3 - Stripe Connect Integration
 * Handles: Stripe Connect onboarding, payment processing,
 * payment intents, and checkout flow
 *
 * NOTE: This module requires the Stripe.js library to be loaded:
 * <script src="https://js.stripe.com/v3/"></script>
 *
 * ============================================================
 * TWO-PARTY STRIPE CONNECT MODEL
 * ============================================================
 *
 * ACCOUNT 1 — Admin Platform Account (Stripe Connect platform)
 *   - The admin/management company creates a standard Stripe account
 *   - Connect is enabled in Settings → Connect settings
 *   - This account receives all guest payments first
 *   - Keeps the management fee (application_fee_amount)
 *   - Publishable key and Connect Client ID come from this account
 *
 * ACCOUNT 2 — Property Owner Connected Account (Express)
 *   - typhoon.tall69@gmail.com creates a Stripe Express account
 *   - Onboarded via an Account Link generated by the platform server
 *   - Receives their share automatically via transfer_data.destination
 *   - Has their own Stripe dashboard to view transfers and manage payouts
 *
 * PAYMENT FLOW (Destination Charges):
 *   Guest pays $1,000
 *     → Platform receives $1,000
 *     → application_fee_amount: $150  (15% admin management fee)
 *     → transfer_data.destination: 'acct_owner_id'  → Owner gets $850
 *     → Stripe fees (~$29.30) come out of the platform's $150 share
 *
 * SERVER-SIDE EXAMPLE (Node.js):
 *
 *   const paymentIntent = await stripe.paymentIntents.create({
 *     amount: 100000,                   // $1,000.00 in cents
 *     currency: 'aud',
 *     payment_method_types: ['card'],
 *     application_fee_amount: 15000,    // 15% = $150.00 admin fee
 *     transfer_data: {
 *       destination: 'acct_conn_9ZyXwVuTsRq',  // owner's connected acct
 *     },
 *     metadata: {
 *       booking_id: 'CA3-20260215',
 *       property: 'Cascade Apartment 3',
 *     },
 *   });
 *   // Return paymentIntent.client_secret to the client
 *
 * OWNER ONBOARDING (server-side):
 *
 *   // 1. Create Express account for owner
 *   const account = await stripe.accounts.create({ type: 'express' });
 *
 *   // 2. Generate onboarding link and email to owner
 *   const accountLink = await stripe.accountLinks.create({
 *     account: account.id,
 *     refresh_url: 'https://yoursite.com/admin/payments',
 *     return_url:  'https://yoursite.com/admin/payments?connected=true',
 *     type: 'account_onboarding',
 *   });
 *   // Redirect owner to: accountLink.url
 *
 * WEBHOOKS TO HANDLE:
 *   - payment_intent.succeeded  → mark booking as paid
 *   - transfer.created          → log owner transfer amount
 *   - account.updated           → update owner account status
 */

(function() {
  'use strict';

  const StripeConnect = {
    stripe: null,
    elements: null,
    cardElement: null,

    // Configuration (would be set from server/environment)
    config: {
      publishableKey: 'pk_test_your_stripe_publishable_key',
      locale: 'en-AU',
      currency: 'aud',
      appearance: {
        theme: 'stripe',
        variables: {
          colorPrimary: '#0f2744',
          colorBackground: '#ffffff',
          colorText: '#2d2926',
          colorDanger: '#e74c3c',
          fontFamily: 'Inter, sans-serif',
          spacingUnit: '4px',
          borderRadius: '8px',
        }
      }
    },

    /**
     * Initialize Stripe — fetches publishable key from /api/stripe-config
     */
    async init() {
      if (typeof Stripe === 'undefined') {
        console.warn('Stripe.js not loaded. Payment processing unavailable.');
        this.showPlaceholder();
        return;
      }

      try {
        const resp = await fetch('/api/stripe-config');
        if (resp.ok) {
          const cfg = await resp.json();
          if (cfg.publishableKey) this.config.publishableKey = cfg.publishableKey;
        }
      } catch (_) {
        // Fallback to hardcoded key (useful for local dev with vercel dev)
      }

      if (!this.config.publishableKey || this.config.publishableKey.startsWith('pk_test_your')) {
        console.warn('Stripe publishable key not configured. Add STRIPE_PUBLISHABLE_KEY to your environment.');
        this.showPlaceholder();
        return;
      }

      try {
        this.stripe = Stripe(this.config.publishableKey);
        this.createElements();
      } catch (e) {
        console.warn('Failed to initialize Stripe:', e.message);
        this.showPlaceholder();
      }
    },

    /**
     * Create Stripe Elements for card input
     */
    createElements() {
      const cardContainer = document.getElementById('stripe-card-element');
      if (!cardContainer || !this.stripe) return;

      this.elements = this.stripe.elements({
        appearance: this.config.appearance
      });

      this.cardElement = this.elements.create('card', {
        style: {
          base: {
            fontSize: '16px',
            color: '#2d2926',
            fontFamily: 'Inter, sans-serif',
            '::placeholder': {
              color: '#b8b0a4',
            },
          },
          invalid: {
            color: '#e74c3c',
          },
        }
      });

      this.cardElement.mount('#stripe-card-element');

      // Handle real-time validation
      this.cardElement.on('change', (event) => {
        const errorEl = document.getElementById('card-errors');
        if (errorEl) {
          errorEl.textContent = event.error ? event.error.message : '';
        }
      });
    },

    /**
     * Show placeholder when Stripe is not loaded or not configured
     */
    showPlaceholder() {
      const cardContainer = document.getElementById('stripe-card-element');
      if (cardContainer) {
        cardContainer.innerHTML = `
          <div style="padding: 16px; border: 2px dashed #e5e7eb; border-radius: 8px; color: #6b7280; font-family: Inter, sans-serif;">
            <p style="font-size: 14px; font-weight: 500; margin: 0 0 4px;">Stripe not configured</p>
            <p style="font-size: 12px; margin: 0; line-height: 1.5;">Add <code style="background:#f3f4f6;padding:1px 4px;border-radius:3px;">STRIPE_PUBLISHABLE_KEY</code> and <code style="background:#f3f4f6;padding:1px 4px;border-radius:3px;">STRIPE_SECRET_KEY</code> in Vercel → Settings → Environment Variables, then redeploy.</p>
          </div>
        `;
      }
      // Disable the Pay button so users get a clear message rather than a JS error
      const payBtn = document.getElementById('payNowBtn');
      if (payBtn) {
        payBtn.disabled = true;
        payBtn.style.opacity = '0.45';
        payBtn.style.cursor = 'not-allowed';
        payBtn.title = 'Add Stripe API keys in Vercel environment variables to enable payments';
      }
    },

    /**
     * Process payment via Stripe Connect Destination Charges.
     *
     * In production this method should:
     *   1. POST booking data to your server endpoint (/api/create-payment-intent)
     *   2. Server creates a PaymentIntent with application_fee_amount and
     *      transfer_data.destination pointing to the owner's connected account
     *   3. Server returns the client_secret
     *   4. Call stripe.confirmCardPayment(clientSecret, { payment_method: { card, billing_details } })
     *
     * Payment split (15% admin / 85% owner by default — configurable in admin):
     *   - application_fee_amount = amount * managementFeePct  → stays with platform
     *   - transfer_data.destination = ownerConnectedAccountId → auto-transferred to owner
     */
    async processPayment(bookingData) {
      if (!this.stripe || !this.cardElement) {
        throw new Error('Payment system is still loading. Please wait a moment and try again.');
      }

      const billingDetails = {
        name: bookingData.cardholderName,
        email: bookingData.email,
        address: {
          line1: bookingData.address,
          city: bookingData.city,
          state: bookingData.state,
          postal_code: bookingData.postcode,
          country: bookingData.country || 'AU',
        }
      };

      // 1. Create a PaymentIntent on the server
      const response = await fetch('/api/create-payment-intent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          amount:    bookingData.amount,       // in cents
          currency:  this.config.currency,
          bookingId: bookingData.bookingId || '',
          email:     bookingData.email,
          checkin:   bookingData.checkin  || '',
          checkout:  bookingData.checkout || '',
          guests:    bookingData.guests   || '',
        }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error || 'Could not create payment session. Please try again.');
      }

      const { clientSecret } = await response.json();

      // 2. Confirm the card payment with Stripe
      const result = await this.stripe.confirmCardPayment(clientSecret, {
        payment_method: {
          card: this.cardElement,
          billing_details: billingDetails,
        },
        receipt_email: bookingData.email,
      });

      if (result.error) {
        throw new Error(result.error.message);
      }

      return {
        success: true,
        paymentIntentId: result.paymentIntent.id,
        status: result.paymentIntent.status,
      };
    },

    /**
     * Start Stripe Connect onboarding for the property owner.
     *
     * In production, the server creates an Express account and Account Link:
     *
     *   const account = await stripe.accounts.create({ type: 'express' });
     *   const link = await stripe.accountLinks.create({
     *     account: account.id,
     *     refresh_url: 'https://yoursite.com/admin/payments',
     *     return_url:  'https://yoursite.com/admin/payments?connected=true',
     *     type: 'account_onboarding',
     *   });
     *   res.json({ url: link.url });
     *
     * Then redirect the owner to link.url for Stripe's hosted onboarding.
     */
    async startOnboarding() {
      console.log('Starting Stripe Connect owner onboarding...');

      // In production: call /api/create-connect-account then redirect to returned URL
      const onboardingUrl = 'https://connect.stripe.com/setup/s/demo';

      window.CascadeApp?.showToast('Generating owner onboarding link...', 'info');

      // In production: window.location.href = onboardingUrl;
      return { url: onboardingUrl };
    },

    /**
     * Check Connect account status
     */
    async checkAccountStatus(accountId) {
      // In production, call your server to check the connected account status
      return {
        accountId: accountId || 'acct_demo',
        chargesEnabled: true,
        payoutsEnabled: true,
        detailsSubmitted: true,
        businessType: 'company',
        created: '2026-01-15'
      };
    },

    /**
     * Create a refund
     */
    async createRefund(paymentIntentId, amount, reason) {
      console.log('Refund would be processed:', {
        paymentIntentId,
        amount,
        reason
      });

      return {
        success: true,
        refundId: 'rf_simulated_' + Date.now(),
        status: 'succeeded'
      };
    }
  };

  // ============================================
  // Checkout Form Handler
  // ============================================
  function initCheckoutForm() {
    const form = document.getElementById('paymentForm');
    if (!form) return;

    form.addEventListener('submit', async (e) => {
      e.preventDefault();

      const submitBtn = document.getElementById('payNowBtn');
      const originalHTML = submitBtn?.innerHTML;
      if (submitBtn) {
        submitBtn.disabled = true;
        submitBtn.innerHTML = '<span style="opacity:.7">Processing payment…</span>';
      }

      // Clear any previous card error
      const errorEl = document.getElementById('card-errors');
      if (errorEl) errorEl.textContent = '';

      try {
        const formData = new FormData(form);
        const data = Object.fromEntries(formData);

        // Read pending booking for email + bookingId
        let pending = {};
        try { pending = JSON.parse(sessionStorage.getItem('ca3_pending_booking') || '{}'); } catch (_) {}

        const result = await StripeConnect.processPayment({
          cardholderName: data.cardHolderName,
          email:          data.bookingEmail  || pending.guestEmail || '',
          address:        data.billingStreet,
          city:           data.billingCity,
          state:          data.billingState,
          postcode:       data.billingPostcode,
          country:        data.billingCountry || 'AU',
          amount:         parseInt(data.bookingAmount) || 0,
          bookingId:      pending.ref || '',
          checkin:        pending.checkin  || '',
          checkout:       pending.checkout || '',
          guests:         pending.guests   || '',
        });

        if (result.success) {
          window.CascadeApp?.showToast('Payment successful!', 'success');

          const ref = (window.CascadeApp?.BookingEngine?.generateReference
            ? window.CascadeApp.BookingEngine.generateReference()
            : 'TRA-' + new Date().getFullYear() + '-' + String(Math.floor(Math.random() * 99999)).padStart(5, '0'));

          const amountCents = parseInt(data.bookingAmount) || 0;
          const totalFormatted = amountCents
            ? new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(amountCents / 100)
            : '';

          const confirmedBooking = {
            ...pending,
            ref,
            paymentIntentId: result.paymentIntentId,
            guestName:    pending.guestName  || data.cardHolderName || 'Guest',
            guestEmail:   pending.guestEmail || data.bookingEmail    || '',
            totalAmount:  totalFormatted,
            paymentStatus: 'paid',
            confirmedAt:  new Date().toISOString(),
          };
          sessionStorage.setItem('ca3_confirmed_booking', JSON.stringify(confirmedBooking));

          // Persist booking to CA3Data (localStorage) so admin panel + calendar reflect it
          if (window.CA3Data) {
            const bookingRecord = {
              id:         ref,
              ref:        ref,
              guestName:  confirmedBooking.guestName,
              guestEmail: confirmedBooking.guestEmail,
              guestPhone: pending.guestPhone || '',
              checkIn:    pending.checkin  || '',
              checkOut:   pending.checkout || '',
              nights:     pending.nights   || 0,
              guests:     pending.guests   || 1,
              status:     'confirmed',
              source:     'direct',
              baseRate:   pending.pricing?.averageNightlyRate || 0,
              total:      amountCents / 100,
              paid:       amountCents / 100,
              deposit:    0,
              paymentIntentId: result.paymentIntentId,
              notes:      pending.specialRequests || '',
            };
            window.CA3Data.addBooking(bookingRecord);
          }

          window.location.href = 'confirmation.html?ref=' + encodeURIComponent(ref);
        }
      } catch (error) {
        const msg = error.message || 'Payment failed. Please try again.';
        if (errorEl) errorEl.textContent = msg;
        window.CascadeApp?.showToast(msg, 'error');
      } finally {
        if (submitBtn) {
          submitBtn.disabled = false;
          submitBtn.innerHTML = originalHTML;
        }
      }
    });
  }

  // ============================================
  // Stripe Connect Admin Handler
  // ============================================
  function initStripeAdmin() {
    const connectBtn = document.getElementById('stripeConnectBtn');
    if (connectBtn) {
      connectBtn.addEventListener('click', async () => {
        await StripeConnect.startOnboarding();
      });
    }

    const disconnectBtn = document.getElementById('stripeDisconnectBtn');
    if (disconnectBtn) {
      disconnectBtn.addEventListener('click', () => {
        if (confirm('Are you sure you want to disconnect your Stripe account?')) {
          window.CascadeApp?.showToast('Stripe account disconnected', 'warning');
        }
      });
    }
  }

  // ============================================
  // Initialize
  // ============================================
  function init() {
    StripeConnect.init();
    initCheckoutForm();
    initStripeAdmin();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

  window.CascadeApp = window.CascadeApp || {};
  window.CascadeApp.StripeConnect = StripeConnect;
})();
